"""added fields

Revision ID: 0c72dd87e0bc
Revises: 
Create Date: 2025-07-01 20:22:12.800345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c72dd87e0bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parkingspots', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=1),
               existing_nullable=False)

    with op.batch_alter_table('reservedparkingspots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserve_timestamp', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('reserve_status', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('vehicle_no', sa.String(length=10), nullable=False))
        batch_op.alter_column('park_timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('leave_timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('park_cost_per_unit_time',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservedparkingspots', schema=None) as batch_op:
        batch_op.alter_column('park_cost_per_unit_time',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('leave_timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('park_timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('vehicle_no')
        batch_op.drop_column('reserve_status')
        batch_op.drop_column('reserve_timestamp')

    with op.batch_alter_table('parkingspots', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=1),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
