"""initial migration

Revision ID: d5009db32a7d
Revises: 
Create Date: 2025-07-21 16:10:06.420333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5009db32a7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('fullname', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('pincode', sa.Integer(), nullable=True, comment='Indian PIN code (100001-999999)'),
    sa.Column('vehicle_no', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('vehicle_no')
    )
    op.create_table('parkinglots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID of row in parkinglots table'),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('prime_loc_name', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('pincode', sa.Integer(), nullable=True, comment='Indian PIN code (100001-999999)'),
    sa.Column('max_spots', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parkingspots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['parkinglots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservedparkingspots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reserve_timestamp', sa.DateTime(), nullable=False),
    sa.Column('park_timestamp', sa.DateTime(), nullable=True),
    sa.Column('leave_timestamp', sa.DateTime(), nullable=True),
    sa.Column('park_cost_per_unit_time', sa.Integer(), nullable=True),
    sa.Column('reserve_status', sa.Boolean(), nullable=False),
    sa.Column('vehicle_no', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['parkingspots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservedparkingspots')
    op.drop_table('parkingspots')
    op.drop_table('parkinglots')
    op.drop_table('users')
    op.drop_table('admins')
    # ### end Alembic commands ###
